spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/biz_exchange?useInformationSchema=true&useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 1qaz